use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    path::{Path, PathBuf},
};

use anyhow::{anyhow, Context, Result};
use clap::{Parser, Subcommand};
use regex::Regex;
use serde::Serialize;

#[derive(Parser, Debug)]
#[command(name = "magicmerlin-sentinel")]
#[command(about = "MagicMerlin parity sentinel (OpenClaw clone correctness)")]
struct Args {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand, Debug)]
enum Command {
    /// Diff OpenClaw gateway method list vs MagicMerlin (implemented endpoints/methods).
    MethodsDiff {
        /// Path to an OpenClaw source checkout.
        #[arg(long, default_value = "../tmp/openclaw-src")]
        openclaw_src: PathBuf,

        /// Emit JSON
        #[arg(long)]
        json: bool,
    },

    /// Generate a docs index from docs.openclaw.ai/llms.txt and persist it.
    /// (Offline mode: provide an existing llms.txt file.)
    DocsIndex {
        /// Path to llms.txt (downloaded).
        #[arg(long)]
        llms_txt: PathBuf,

        /// Output json path.
        #[arg(long, default_value = "parity/openclaw_docs_index.json")]
        out: PathBuf,
    },

    /// Diff docs index against MagicMerlin parity checklist.
    DocsDiff {
        /// Docs index json generated by `docs-index`.
        #[arg(long, default_value = "parity/openclaw_docs_index.json")]
        index: PathBuf,

        /// Parity checklist yaml/json (we start with json).
        #[arg(long, default_value = "parity/docs_coverage.json")]
        coverage: PathBuf,

        /// Emit JSON
        #[arg(long)]
        json: bool,
    },

    /// Diff OpenClaw CLI command tree snapshot vs MagicMerlin CLI surface.
    CliDiff {
        /// Path to MagicMerlin compat snapshot help tree json.
        #[arg(
            long,
            default_value = "compat/snapshots/2026-03-02_openclaw_help_tree.json"
        )]
        openclaw_help_tree: PathBuf,

        /// Emit JSON
        #[arg(long)]
        json: bool,
    },
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
struct DiffReport {
    title: String,
    ok: bool,
    have: Vec<String>,
    want: Vec<String>,
    missing: Vec<String>,
    extra: Vec<String>,
    notes: Vec<String>,
}

fn read_to_string(path: &Path) -> Result<String> {
    fs::read_to_string(path).with_context(|| format!("read {}", path.display()))
}

fn extract_openclaw_gateway_methods(openclaw_src: &Path) -> Result<BTreeSet<String>> {
    let path = openclaw_src.join("src/gateway/server-methods-list.ts");
    let raw = read_to_string(&path)?;

    // Extremely conservative: only parse string literals inside BASE_METHODS.
    // We intentionally ignore channel plugin injection for now (extensions).
    let mut in_base = false;
    let mut methods = BTreeSet::new();
    let re = Regex::new(r#"^\s*"([^"]+)",?\s*$"#).unwrap();

    for line in raw.lines() {
        if line.contains("const BASE_METHODS") {
            in_base = true;
            continue;
        }
        if in_base && line.contains("];") {
            break;
        }
        if !in_base {
            continue;
        }
        if let Some(c) = re.captures(line) {
            methods.insert(c[1].to_string());
        }
    }

    if methods.is_empty() {
        return Err(anyhow!(
            "failed to parse BASE_METHODS from {}",
            path.display()
        ));
    }

    Ok(methods)
}

fn magicmerlin_gateway_methods_current() -> BTreeSet<String> {
    // As of now, MagicMerlin does NOT have an OpenClaw-style /call RPC surface.
    // We track parity by mapping existing HTTP endpoints to method names.
    // This list will be replaced by real method routing once implemented.
    BTreeSet::from([
        "health".to_string(),
        "status".to_string(),
        "cron.list".to_string(),
        "cron.run".to_string(),
        "cron.pause".to_string(),
        "cron.resume".to_string(),
        "cron.deadLetters".to_string(),
        "sessions.list".to_string(),
        "sessions.get".to_string(),
        "approvals.get".to_string(),
        "plugins.list".to_string(),
        "chat".to_string(),
    ])
}

fn load_openclaw_docs_index(path: &Path) -> Result<BTreeSet<String>> {
    let raw = read_to_string(path)?;
    let v: serde_json::Value = serde_json::from_str(&raw).context("parse docs index json")?;
    let mut out = BTreeSet::new();
    let Some(arr) = v.get("pages").and_then(|x| x.as_array()) else {
        return Err(anyhow!("docs index missing pages[]"));
    };
    for p in arr {
        if let Some(url) = p.get("url").and_then(|x| x.as_str()) {
            out.insert(url.to_string());
        }
    }
    Ok(out)
}

fn load_docs_coverage(path: &Path) -> Result<BTreeMap<String, String>> {
    if !path.exists() {
        return Ok(BTreeMap::new());
    }
    let raw = read_to_string(path)?;
    let v: serde_json::Value = serde_json::from_str(&raw).context("parse docs coverage")?;
    let Some(obj) = v.as_object() else {
        return Err(anyhow!(
            "docs coverage must be a JSON object mapping url -> status (done|todo|partial)"
        ));
    };
    let mut out = BTreeMap::new();
    for (k, v) in obj {
        out.insert(k.clone(), v.as_str().unwrap_or("unknown").to_string());
    }
    Ok(out)
}

fn save_default_docs_coverage(path: &Path, index_pages: &BTreeSet<String>) -> Result<()> {
    if path.exists() {
        return Ok(());
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).ok();
    }
    let mut m = serde_json::Map::new();
    for url in index_pages {
        m.insert(url.clone(), serde_json::Value::String("todo".to_string()));
    }
    fs::write(
        path,
        serde_json::to_string_pretty(&serde_json::Value::Object(m))? + "\n",
    )
    .context("write docs coverage")?;
    Ok(())
}

fn parse_llms_txt_to_pages(llms: &str) -> Vec<(String, String)> {
    // Returns (title, url)
    let re = Regex::new(r#"^- \[(.+?)\]\((https?://[^\)]+)\)"#).unwrap();
    let mut pages = Vec::new();
    for line in llms.lines() {
        if let Some(c) = re.captures(line.trim()) {
            pages.push((c[1].to_string(), c[2].to_string()));
        }
    }
    pages
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct DocsIndexFile {
    generated_at: String,
    pages: Vec<DocsIndexPage>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct DocsIndexPage {
    title: String,
    url: String,
}

fn main() -> Result<()> {
    let args = Args::parse();

    match args.command {
        Command::MethodsDiff { openclaw_src, json } => {
            let want = extract_openclaw_gateway_methods(&openclaw_src)?;
            let have = magicmerlin_gateway_methods_current();

            let missing: Vec<String> = want.difference(&have).cloned().collect();
            let extra: Vec<String> = have.difference(&want).cloned().collect();

            let report = DiffReport {
                title: "gateway.methods".to_string(),
                ok: missing.is_empty(),
                have: have.iter().cloned().collect(),
                want: want.iter().cloned().collect(),
                missing,
                extra,
                notes: vec![
                    "MagicMerlin currently exposes HTTP endpoints, not OpenClaw's /call RPC method surface.".to_string(),
                    "Next step: implement /call {method, params} to route methods and make this diff meaningful.".to_string(),
                ],
            };

            if json {
                println!("{}", serde_json::to_string_pretty(&report)?);
            } else {
                println!("{}: ok={}", report.title, report.ok);
                println!("missing: {}", report.missing.len());
                for m in report.missing.iter().take(40) {
                    println!("  - {m}");
                }
                if report.missing.len() > 40 {
                    println!("  ... ({} more)", report.missing.len() - 40);
                }
            }

            if !report.ok {
                std::process::exit(2);
            }
            Ok(())
        }

        Command::DocsIndex { llms_txt, out } => {
            let llms = read_to_string(&llms_txt)?;
            let pages = parse_llms_txt_to_pages(&llms)
                .into_iter()
                .map(|(title, url)| DocsIndexPage { title, url })
                .collect::<Vec<_>>();

            let idx = DocsIndexFile {
                generated_at: chrono::Utc::now().to_rfc3339(),
                pages,
            };

            if let Some(parent) = out.parent() {
                fs::create_dir_all(parent).ok();
            }
            fs::write(&out, serde_json::to_string_pretty(&idx)? + "\n")
                .with_context(|| format!("write {}", out.display()))?;

            println!("wrote {}", out.display());
            Ok(())
        }

        Command::DocsDiff {
            index,
            coverage,
            json,
        } => {
            let pages = load_openclaw_docs_index(&index)?;
            let cov = load_docs_coverage(&coverage)?;
            save_default_docs_coverage(&coverage, &pages)?;

            let want: BTreeSet<String> = pages.iter().cloned().collect();
            let have: BTreeSet<String> = cov
                .iter()
                .filter_map(|(url, status)| {
                    if status == "done" {
                        Some(url.clone())
                    } else {
                        None
                    }
                })
                .collect();

            let missing: Vec<String> = want.difference(&have).cloned().collect();
            let extra: Vec<String> = have.difference(&want).cloned().collect();

            let report = DiffReport {
                title: "docs.coverage".to_string(),
                ok: missing.is_empty(),
                have: have.iter().cloned().collect(),
                want: want.iter().cloned().collect(),
                missing,
                extra,
                notes: vec![format!(
                    "coverage file: {} (auto-created if missing). Mark URLs as 'done' to clear missing list.",
                    coverage.display()
                )],
            };

            if json {
                println!("{}", serde_json::to_string_pretty(&report)?);
            } else {
                println!("{}: ok={}", report.title, report.ok);
                println!("done: {} / {}", report.have.len(), report.want.len());
                println!("missing: {}", report.missing.len());
            }

            if !report.ok {
                std::process::exit(2);
            }
            Ok(())
        }

        Command::CliDiff {
            openclaw_help_tree,
            json,
        } => {
            let raw = read_to_string(&openclaw_help_tree)?;
            let v: serde_json::Value = serde_json::from_str(&raw).context("parse help tree")?;

            // The help tree JSON is produced by our capture script.
            // Current format:
            // {
            //   "commands": {
            //     "cron": {"subcommands": {"list": {...}}},
            //     ...
            //   }
            // }
            fn walk_help_tree(
                node: &serde_json::Value,
                prefix: Vec<String>,
                out: &mut BTreeSet<String>,
            ) {
                let Some(obj) = node.as_object() else {
                    return;
                };

                for (name, entry) in obj {
                    let mut p = prefix.clone();
                    p.push(name.to_string());
                    out.insert(p.join(" "));

                    if let Some(sub) = entry.get("subcommands") {
                        walk_help_tree(sub, p, out);
                    }
                }
            }

            let mut want = BTreeSet::new();
            if let Some(cmds) = v.get("commands") {
                walk_help_tree(cmds, vec![], &mut want);
            }

            if want.is_empty() {
                return Err(anyhow!("help tree had no commands; unexpected format"));
            }

            // Current MagicMerlin CLI surface (minimal; will be expanded to match OpenClaw).
            let have = BTreeSet::from([
                "onboard".to_string(),
                "gateway".to_string(),
                "gateway status".to_string(),
                "gateway run".to_string(),
                "dashboard".to_string(),
                "message".to_string(),
                "message send".to_string(),
            ]);

            let missing: Vec<String> = want.difference(&have).cloned().collect();
            let extra: Vec<String> = have.difference(&want).cloned().collect();

            let report = DiffReport {
                title: "cli.commands".to_string(),
                ok: missing.is_empty(),
                have: have.iter().cloned().collect(),
                want: want.iter().cloned().collect(),
                missing,
                extra,
                notes: vec![
                    "This is a coarse diff today (MagicMerlin has only a subset).".to_string(),
                    "As we add commands, this check becomes the gate to '100% CLI parity'."
                        .to_string(),
                ],
            };

            if json {
                println!("{}", serde_json::to_string_pretty(&report)?);
            } else {
                println!("{}: ok={}", report.title, report.ok);
                println!("missing: {}", report.missing.len());
                for m in report.missing.iter().take(30) {
                    println!("  - {m}");
                }
            }

            if !report.ok {
                std::process::exit(2);
            }
            Ok(())
        }
    }
}
