use std::collections::BTreeMap;
use std::path::PathBuf;

use magicmerlin_agent::{
    run_heartbeat_with_state, AgentConfig, AgentDescriptor, AgentRegistry, HeartbeatState,
    InboundContext, PromptRuntimeMetadata, SessionKey, SessionManager, SystemPromptAssembler,
    ToolSchemaDescriptor,
};
use magicmerlin_storage::Storage;
use serde_json::json;

#[derive(Debug, Clone)]
struct RouteScenario {
    name: &'static str,
    channel: &'static str,
    text: &'static str,
    workspace_hint: Option<&'static str>,
    expected_agent: &'static str,
    min_confidence: u8,
}

fn build_registry() -> AgentRegistry {
    let agents = vec![
        AgentDescriptor {
            id: "merlin".to_string(),
            workspace_dir: PathBuf::from("/tmp/ws-merlin"),
            agent_dir: PathBuf::from("/tmp/agent-merlin"),
            sessions_dir: PathBuf::from("/tmp/agent-merlin/sessions"),
            config: AgentConfig {
                identity_emoji: Some("wizard".to_string()),
                ..AgentConfig::default()
            },
            last_health_check_epoch: 0,
        },
        AgentDescriptor {
            id: "helper".to_string(),
            workspace_dir: PathBuf::from("/tmp/ws-helper"),
            agent_dir: PathBuf::from("/tmp/agent-helper"),
            sessions_dir: PathBuf::from("/tmp/agent-helper/sessions"),
            config: AgentConfig {
                identity_emoji: Some("gear".to_string()),
                ..AgentConfig::default()
            },
            last_health_check_epoch: 0,
        },
    ];

    let mut registry = AgentRegistry::default();
    for descriptor in agents {
        registry.upsert(descriptor);
    }
    registry
}

#[test]
fn route_matrix_coverage() {
    let registry = build_registry();
    let scenarios = vec![
        RouteScenario {
            name: "mention_merlin_1",
            channel: "telegram",
            text: "please ask merlin about task 1",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_2",
            channel: "web",
            text: "unattributed event 2",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_3",
            channel: "terminal",
            text: "general message 3",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_4",
            channel: "telegram",
            text: "please ask merlin about task 4",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_5",
            channel: "web",
            text: "unattributed event 5",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_6",
            channel: "terminal",
            text: "general message 6",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_7",
            channel: "telegram",
            text: "please ask merlin about task 7",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_8",
            channel: "web",
            text: "unattributed event 8",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_9",
            channel: "terminal",
            text: "general message 9",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_10",
            channel: "telegram",
            text: "please ask merlin about task 10",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_11",
            channel: "web",
            text: "unattributed event 11",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_12",
            channel: "terminal",
            text: "general message 12",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_13",
            channel: "telegram",
            text: "please ask merlin about task 13",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_14",
            channel: "web",
            text: "unattributed event 14",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_15",
            channel: "terminal",
            text: "general message 15",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_16",
            channel: "telegram",
            text: "please ask merlin about task 16",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_17",
            channel: "web",
            text: "unattributed event 17",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_18",
            channel: "terminal",
            text: "general message 18",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_19",
            channel: "telegram",
            text: "please ask merlin about task 19",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_20",
            channel: "web",
            text: "unattributed event 20",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_21",
            channel: "terminal",
            text: "general message 21",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_22",
            channel: "telegram",
            text: "please ask merlin about task 22",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_23",
            channel: "web",
            text: "unattributed event 23",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_24",
            channel: "terminal",
            text: "general message 24",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_25",
            channel: "telegram",
            text: "please ask merlin about task 25",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_26",
            channel: "web",
            text: "unattributed event 26",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_27",
            channel: "terminal",
            text: "general message 27",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_28",
            channel: "telegram",
            text: "please ask merlin about task 28",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_29",
            channel: "web",
            text: "unattributed event 29",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_30",
            channel: "terminal",
            text: "general message 30",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_31",
            channel: "telegram",
            text: "please ask merlin about task 31",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_32",
            channel: "web",
            text: "unattributed event 32",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_33",
            channel: "terminal",
            text: "general message 33",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_34",
            channel: "telegram",
            text: "please ask merlin about task 34",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_35",
            channel: "web",
            text: "unattributed event 35",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_36",
            channel: "terminal",
            text: "general message 36",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_37",
            channel: "telegram",
            text: "please ask merlin about task 37",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_38",
            channel: "web",
            text: "unattributed event 38",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_39",
            channel: "terminal",
            text: "general message 39",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_40",
            channel: "telegram",
            text: "please ask merlin about task 40",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_41",
            channel: "web",
            text: "unattributed event 41",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_42",
            channel: "terminal",
            text: "general message 42",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_43",
            channel: "telegram",
            text: "please ask merlin about task 43",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_44",
            channel: "web",
            text: "unattributed event 44",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_45",
            channel: "terminal",
            text: "general message 45",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_46",
            channel: "telegram",
            text: "please ask merlin about task 46",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_47",
            channel: "web",
            text: "unattributed event 47",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_48",
            channel: "terminal",
            text: "general message 48",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_49",
            channel: "telegram",
            text: "please ask merlin about task 49",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_50",
            channel: "web",
            text: "unattributed event 50",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_51",
            channel: "terminal",
            text: "general message 51",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_52",
            channel: "telegram",
            text: "please ask merlin about task 52",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_53",
            channel: "web",
            text: "unattributed event 53",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_54",
            channel: "terminal",
            text: "general message 54",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_55",
            channel: "telegram",
            text: "please ask merlin about task 55",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_56",
            channel: "web",
            text: "unattributed event 56",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_57",
            channel: "terminal",
            text: "general message 57",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_58",
            channel: "telegram",
            text: "please ask merlin about task 58",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_59",
            channel: "web",
            text: "unattributed event 59",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_60",
            channel: "terminal",
            text: "general message 60",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_61",
            channel: "telegram",
            text: "please ask merlin about task 61",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_62",
            channel: "web",
            text: "unattributed event 62",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_63",
            channel: "terminal",
            text: "general message 63",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_64",
            channel: "telegram",
            text: "please ask merlin about task 64",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_65",
            channel: "web",
            text: "unattributed event 65",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_66",
            channel: "terminal",
            text: "general message 66",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_67",
            channel: "telegram",
            text: "please ask merlin about task 67",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_68",
            channel: "web",
            text: "unattributed event 68",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_69",
            channel: "terminal",
            text: "general message 69",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_70",
            channel: "telegram",
            text: "please ask merlin about task 70",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_71",
            channel: "web",
            text: "unattributed event 71",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_72",
            channel: "terminal",
            text: "general message 72",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_73",
            channel: "telegram",
            text: "please ask merlin about task 73",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_74",
            channel: "web",
            text: "unattributed event 74",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_75",
            channel: "terminal",
            text: "general message 75",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_76",
            channel: "telegram",
            text: "please ask merlin about task 76",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_77",
            channel: "web",
            text: "unattributed event 77",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_78",
            channel: "terminal",
            text: "general message 78",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_79",
            channel: "telegram",
            text: "please ask merlin about task 79",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_80",
            channel: "web",
            text: "unattributed event 80",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_81",
            channel: "terminal",
            text: "general message 81",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_82",
            channel: "telegram",
            text: "please ask merlin about task 82",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_83",
            channel: "web",
            text: "unattributed event 83",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_84",
            channel: "terminal",
            text: "general message 84",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_85",
            channel: "telegram",
            text: "please ask merlin about task 85",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_86",
            channel: "web",
            text: "unattributed event 86",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_87",
            channel: "terminal",
            text: "general message 87",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_88",
            channel: "telegram",
            text: "please ask merlin about task 88",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_89",
            channel: "web",
            text: "unattributed event 89",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_90",
            channel: "terminal",
            text: "general message 90",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_91",
            channel: "telegram",
            text: "please ask merlin about task 91",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_92",
            channel: "web",
            text: "unattributed event 92",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_93",
            channel: "terminal",
            text: "general message 93",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_94",
            channel: "telegram",
            text: "please ask merlin about task 94",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_95",
            channel: "web",
            text: "unattributed event 95",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_96",
            channel: "terminal",
            text: "general message 96",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_97",
            channel: "telegram",
            text: "please ask merlin about task 97",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_98",
            channel: "web",
            text: "unattributed event 98",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_99",
            channel: "terminal",
            text: "general message 99",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_100",
            channel: "telegram",
            text: "please ask merlin about task 100",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_101",
            channel: "web",
            text: "unattributed event 101",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_102",
            channel: "terminal",
            text: "general message 102",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_103",
            channel: "telegram",
            text: "please ask merlin about task 103",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_104",
            channel: "web",
            text: "unattributed event 104",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_105",
            channel: "terminal",
            text: "general message 105",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_106",
            channel: "telegram",
            text: "please ask merlin about task 106",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_107",
            channel: "web",
            text: "unattributed event 107",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_108",
            channel: "terminal",
            text: "general message 108",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_109",
            channel: "telegram",
            text: "please ask merlin about task 109",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_110",
            channel: "web",
            text: "unattributed event 110",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_111",
            channel: "terminal",
            text: "general message 111",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_112",
            channel: "telegram",
            text: "please ask merlin about task 112",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_113",
            channel: "web",
            text: "unattributed event 113",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_114",
            channel: "terminal",
            text: "general message 114",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_115",
            channel: "telegram",
            text: "please ask merlin about task 115",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_116",
            channel: "web",
            text: "unattributed event 116",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_117",
            channel: "terminal",
            text: "general message 117",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_118",
            channel: "telegram",
            text: "please ask merlin about task 118",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_119",
            channel: "web",
            text: "unattributed event 119",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_120",
            channel: "terminal",
            text: "general message 120",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_121",
            channel: "telegram",
            text: "please ask merlin about task 121",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_122",
            channel: "web",
            text: "unattributed event 122",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_123",
            channel: "terminal",
            text: "general message 123",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_124",
            channel: "telegram",
            text: "please ask merlin about task 124",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_125",
            channel: "web",
            text: "unattributed event 125",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_126",
            channel: "terminal",
            text: "general message 126",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_127",
            channel: "telegram",
            text: "please ask merlin about task 127",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_128",
            channel: "web",
            text: "unattributed event 128",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_129",
            channel: "terminal",
            text: "general message 129",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_130",
            channel: "telegram",
            text: "please ask merlin about task 130",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_131",
            channel: "web",
            text: "unattributed event 131",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_132",
            channel: "terminal",
            text: "general message 132",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_133",
            channel: "telegram",
            text: "please ask merlin about task 133",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_134",
            channel: "web",
            text: "unattributed event 134",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_135",
            channel: "terminal",
            text: "general message 135",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_136",
            channel: "telegram",
            text: "please ask merlin about task 136",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_137",
            channel: "web",
            text: "unattributed event 137",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_138",
            channel: "terminal",
            text: "general message 138",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_139",
            channel: "telegram",
            text: "please ask merlin about task 139",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_140",
            channel: "web",
            text: "unattributed event 140",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_141",
            channel: "terminal",
            text: "general message 141",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_142",
            channel: "telegram",
            text: "please ask merlin about task 142",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_143",
            channel: "web",
            text: "unattributed event 143",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_144",
            channel: "terminal",
            text: "general message 144",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_145",
            channel: "telegram",
            text: "please ask merlin about task 145",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_146",
            channel: "web",
            text: "unattributed event 146",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_147",
            channel: "terminal",
            text: "general message 147",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_148",
            channel: "telegram",
            text: "please ask merlin about task 148",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_149",
            channel: "web",
            text: "unattributed event 149",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_150",
            channel: "terminal",
            text: "general message 150",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_151",
            channel: "telegram",
            text: "please ask merlin about task 151",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_152",
            channel: "web",
            text: "unattributed event 152",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_153",
            channel: "terminal",
            text: "general message 153",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_154",
            channel: "telegram",
            text: "please ask merlin about task 154",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_155",
            channel: "web",
            text: "unattributed event 155",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_156",
            channel: "terminal",
            text: "general message 156",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_157",
            channel: "telegram",
            text: "please ask merlin about task 157",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_158",
            channel: "web",
            text: "unattributed event 158",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_159",
            channel: "terminal",
            text: "general message 159",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_160",
            channel: "telegram",
            text: "please ask merlin about task 160",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_161",
            channel: "web",
            text: "unattributed event 161",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_162",
            channel: "terminal",
            text: "general message 162",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_163",
            channel: "telegram",
            text: "please ask merlin about task 163",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_164",
            channel: "web",
            text: "unattributed event 164",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_165",
            channel: "terminal",
            text: "general message 165",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_166",
            channel: "telegram",
            text: "please ask merlin about task 166",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_167",
            channel: "web",
            text: "unattributed event 167",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_168",
            channel: "terminal",
            text: "general message 168",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_169",
            channel: "telegram",
            text: "please ask merlin about task 169",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_170",
            channel: "web",
            text: "unattributed event 170",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_171",
            channel: "terminal",
            text: "general message 171",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_172",
            channel: "telegram",
            text: "please ask merlin about task 172",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_173",
            channel: "web",
            text: "unattributed event 173",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_174",
            channel: "terminal",
            text: "general message 174",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_175",
            channel: "telegram",
            text: "please ask merlin about task 175",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_176",
            channel: "web",
            text: "unattributed event 176",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_177",
            channel: "terminal",
            text: "general message 177",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_178",
            channel: "telegram",
            text: "please ask merlin about task 178",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_179",
            channel: "web",
            text: "unattributed event 179",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_180",
            channel: "terminal",
            text: "general message 180",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_181",
            channel: "telegram",
            text: "please ask merlin about task 181",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_182",
            channel: "web",
            text: "unattributed event 182",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_183",
            channel: "terminal",
            text: "general message 183",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_184",
            channel: "telegram",
            text: "please ask merlin about task 184",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_185",
            channel: "web",
            text: "unattributed event 185",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_186",
            channel: "terminal",
            text: "general message 186",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_187",
            channel: "telegram",
            text: "please ask merlin about task 187",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_188",
            channel: "web",
            text: "unattributed event 188",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_189",
            channel: "terminal",
            text: "general message 189",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_190",
            channel: "telegram",
            text: "please ask merlin about task 190",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_191",
            channel: "web",
            text: "unattributed event 191",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_192",
            channel: "terminal",
            text: "general message 192",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_193",
            channel: "telegram",
            text: "please ask merlin about task 193",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_194",
            channel: "web",
            text: "unattributed event 194",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_195",
            channel: "terminal",
            text: "general message 195",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_196",
            channel: "telegram",
            text: "please ask merlin about task 196",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_197",
            channel: "web",
            text: "unattributed event 197",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_198",
            channel: "terminal",
            text: "general message 198",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_199",
            channel: "telegram",
            text: "please ask merlin about task 199",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_200",
            channel: "web",
            text: "unattributed event 200",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_201",
            channel: "terminal",
            text: "general message 201",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_202",
            channel: "telegram",
            text: "please ask merlin about task 202",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_203",
            channel: "web",
            text: "unattributed event 203",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_204",
            channel: "terminal",
            text: "general message 204",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_205",
            channel: "telegram",
            text: "please ask merlin about task 205",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_206",
            channel: "web",
            text: "unattributed event 206",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_207",
            channel: "terminal",
            text: "general message 207",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_208",
            channel: "telegram",
            text: "please ask merlin about task 208",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_209",
            channel: "web",
            text: "unattributed event 209",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_210",
            channel: "terminal",
            text: "general message 210",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_211",
            channel: "telegram",
            text: "please ask merlin about task 211",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_212",
            channel: "web",
            text: "unattributed event 212",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_213",
            channel: "terminal",
            text: "general message 213",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_214",
            channel: "telegram",
            text: "please ask merlin about task 214",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_215",
            channel: "web",
            text: "unattributed event 215",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_216",
            channel: "terminal",
            text: "general message 216",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_217",
            channel: "telegram",
            text: "please ask merlin about task 217",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
        RouteScenario {
            name: "fallback_218",
            channel: "web",
            text: "unattributed event 218",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 50,
        },
        RouteScenario {
            name: "workspace_match_219",
            channel: "terminal",
            text: "general message 219",
            workspace_hint: Some("/tmp/ws-helper"),
            expected_agent: "helper",
            min_confidence: 90,
        },
        RouteScenario {
            name: "mention_merlin_220",
            channel: "telegram",
            text: "please ask merlin about task 220",
            workspace_hint: None,
            expected_agent: "merlin",
            min_confidence: 80,
        },
    ];

    for scenario in scenarios {
        let workspace_hint = scenario.workspace_hint.map(PathBuf::from);
        let decision = registry
            .route_message(
                scenario.channel,
                workspace_hint.as_deref(),
                scenario.text,
            )
            .expect("decision");
        if !scenario.name.starts_with("fallback_") {
            assert_eq!(
                decision.agent_id, scenario.expected_agent,
                "scenario {}",
                scenario.name
            );
        }
        assert!(
            decision.confidence >= scenario.min_confidence,
            "scenario {} confidence {} < {}",
            scenario.name,
            decision.confidence,
            scenario.min_confidence
        );
    }
}

#[test]
fn prompt_assembly_matrix() {
    let temp = tempfile::tempdir().expect("tmp");
    std::fs::write(temp.path().join("AGENTS.md"), "# Agent\nYou are merlin.").expect("write");
    std::fs::write(temp.path().join("MEMORY.md"), "# Memory\nRecent tasks.").expect("write");

    let assembler = SystemPromptAssembler::new(temp.path(), temp.path(), 8000);

    let mut inbound = InboundContext::default();
    inbound.sender_id = Some("u-1".to_string());
    inbound.sender_name = Some("Alice".to_string());
    inbound.chat_type = Some("group".to_string());
    inbound.reply_to = Some("m-12".to_string());
    inbound.extra = {
        let mut extra = BTreeMap::new();
        extra.insert("thread".to_string(), json!("abc"));
        extra
    };

    let tools = vec![
        ToolSchemaDescriptor {
            name: "exec".to_string(),
            description: "execute shell".to_string(),
            parameters: json!({"type":"object","properties":{"cmd":{"type":"string"}}}),
        },
        ToolSchemaDescriptor {
            name: "search".to_string(),
            description: "search docs".to_string(),
            parameters: json!({"type":"object","properties":{"q":{"type":"string"}}}),
        },
    ];

    for idx in 0..120 {
        let prompt = assembler
            .assemble_with_context(
                &PromptRuntimeMetadata::now(
                    "openai/gpt-5.2".to_string(),
                    if idx % 2 == 0 { "terminal" } else { "telegram" }.to_string(),
                    "America/New_York".to_string(),
                    "merlin".to_string(),
                ),
                &inbound,
                &tools,
            )
            .expect("prompt");

        assert!(prompt.contains("<runtime>"));
        assert!(prompt.contains("<tool_schemas>"));
        assert!(prompt.contains("Alice"));
        assert!(prompt.contains("exec"));
    }
}

#[test]
fn heartbeat_and_session_matrix() {
    let temp = tempfile::tempdir().expect("tmp");
    std::fs::write(
        temp.path().join("HEARTBEAT.md"),
        "- [ ] memory refresh\n- [ ] session compaction\n- [ ] queue health\n",
    )
    .expect("write");

    let mut state = HeartbeatState::default();
    for _ in 0..40 {
        let run = run_heartbeat_with_state(temp.path(), Some(23), Some(5), &mut state)
            .expect("run");
        if run.quiet_hours {
            assert!(run.tasks_to_run.is_empty());
        } else {
            assert!(!run.tasks_to_run.is_empty());
        }
    }

    let storage = Storage::new(temp.path().join("db.sqlite")).expect("storage");
    let sessions = SessionManager::new(storage, temp.path().join("sessions"), temp.path())
        .expect("sessions");
    let mut session = sessions
        .load_or_create(SessionKey::agent_main("merlin"), "merlin")
        .expect("session");

    for i in 0..160 {
        sessions
            .append_message(
                &mut session,
                json!({"role":"user","content":format!("remember TODO item {i}")}),
            )
            .expect("append");
    }

    let compaction = sessions
        .compact_if_needed(&mut session, 200, 60)
        .expect("compact");
    assert!(compaction.is_some());
    assert!(session.metadata.compaction_count > 0);
}
